export enum NAVIGATION_ROUTES {
  HOME_SCREEN = 'HOME_SCREEN',
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  HOME_NAVIGATOR = 'HOME_NAVIGATOR',
  LABEL_NAVIGATOR = 'LABEL_NAVIGATOR',
  USER_NAVIGATOR = 'USER_NAVIGATOR',
  GIFT_NAVIGATOR = 'GIFT_NAVIGATOR',
  GIFT_SCREEN = 'GIFT_SCREEN',
  USER_SCREEN = 'USER_SCREEN',
  LABEL_SCREEN = 'LABEL_SCREEN',
}
